### ISSUE TITLE
Add flag view and deletion feature

### ISSUE THREAD

**Issue by rotsee** [fruktkartan/fruktsam#1]
The API (dev) now has endpoints for flagging trees for deletion (to be called from frontend), listing flags and removing a flag.

Deleting a tree will also remove all associated flag.

It would be nice to have a “flagged trees view”, showing all flags, and allowing us to take action (by deleting a flagged tree, or deleting the flag). Flags are listed at (dev) https://fruktkartan-api-dev.herokuapp.com/flags and eventually (prod) https://fruktkartan-api.herokuapp.com/flags

To delete a flag: [DEL] `/flag/{TREE-ID}/{FLAG-NAME}` , e.g. /flag/12345/delete

To delete a tree: [DEL] `/tree/{TREE-ID}` , e.g. /tree/12345

See https://github.com/fruktkartan/fruktkartan-api/issues/26

**Comment by quite** [comment]
I tried adding output of trees from flags table, branch is here: https://github.com/fruktkartan/fruktsam/tree/flagdelete

Works and outputs 1 tree when run towards the dev db

**Comment by rotsee** [comment]
That was quick! I'll add the frontend feature (https://github.com/fruktkartan/fruktkartan/issues/95) later this week, and then we can test the whole chain
